### ISSUE TITLE
Change the data pattern in Authorizable.sol to avoid using loops and save gas

### ISSUE THREAD

**Issue by zemingyu** [8xprotocol/contracts#23]
We can update `removeAuthorizedAddress()` and `addAuthorizedAddress()` to save a lot of gas.

Loops like this costs a lot of gas
https://github.com/8x-protocol/8x-protocol/blob/bfe07a8f3233ef623bafd8bc20a9a1c9155b9d16/contracts/Authorizable.sol#L62

This can be avoided by setting up a struct like this
```
    struct Member {
        bool exists;
        uint index;
        string name;
    }
```

And later on only check if the entry exists or not.
By default solidity maps all keys to 0 / False. So if the data hasn't been stored, it will return a false by default.

```
    function add(Data storage self, address memberAddress, string memberName) internal {
        require(!self.entries[memberAddress].exists);
        self.index.push(memberAddress);
        self.entries[memberAddress] = Member(true, self.index.length - 1, memberName);
        emit MemberAdded(memberAddress, memberName, self.index.length);
    }
    function remove(Data storage self, address memberAddress) internal {
        require(self.entries[memberAddress].exists);
        uint removeIndex = self.entries[memberAddress].index;
        emit MemberRemoved(memberAddress, self.entries[memberAddress].name, self.index.length - 1);
        uint lastIndex = self.index.length - 1;
        address lastIndexAddress = self.index[lastIndex];
        self.index[removeIndex] = lastIndexAddress;
        self.entries[lastIndexAddress].index = removeIndex;
        delete self.entries[memberAddress];
        if (self.index.length > 0) {
            self.index.length--;
        }
    }
```
Source:
https://github.com/bokkypoobah/ClubEth/blob/396dbfd371843ced50c5613867d8101887d77270/contracts/ClubEthFactory.sol#L202

**Comment by kermankohli** [comment]
While this is a valid concern, it has already been implemented in the exisiting Authorizable.sol file :)

**Comment by zemingyu** [comment]
Hi Kerman,

I still think this line can be optimised to avoid the loop...

https://github.com/8x-protocol/8x-protocol/blob/bfe07a8f3233ef623bafd8bc20a9a1c9155b9d16/contracts/Authorizable.sol#L62

**Comment by kermankohli** [comment]
Made more sense after chatting to you. It's a bit of a small optimisation but since we're reusing it in a bunch of places it might be worth it :)

**Comment by zemingyu** [comment]
Yeah, sometimes it's better to chat face to face...
