### ISSUE TITLE
PaymentRegistry implementation

### ISSUE THREAD

**Issue by travisdmathis** [8xprotocol/contracts#8]
We need to complete the TODO sections in PaymentRegistry.  Functionality can be confirmed by looking at the PaymentRegistry tests.

- [ ] setMultiplier
- [ ] createNewPayment
- [ ] processPayment
- [ ] removeClaimant
- [ ] cancelPayment
- [ ] getPaymentInformation

**Comment by zemingyu** [comment]
Adding a to-do item
- [ ] multiplier is uint at the moment. It needs to handle, say, two decimal places.
